//! AuraOS Multi-Modal Input System
//! 
//! Fuses multiple input sources into a unified intent stream:
//! - Keyboard & mouse (traditional)
//! - Touch & gesture (tablet/touchscreen)
//! - Voice (always-on with wake word)
//! - Gaze tracking (eye tracking hardware)
//! - Gamepad/controller
//! 
//! All input becomes "Intent" — the system doesn't care HOW you expressed it.

pub mod keyboard;
pub mod mouse;
pub mod touch;
pub mod voice;
pub mod gesture;

/// A unified input event from any source
#[derive(Debug, Clone)]
pub struct InputEvent {
    pub timestamp_ns: u64,
    pub source: InputSource,
    pub kind: InputKind,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InputSource {
    Keyboard,
    Mouse,
    Touchscreen,
    Trackpad,
    Voice,
    Gaze,
    Gamepad,
    Stylus,
    System,     // Generated by the OS itself
}

#[derive(Debug, Clone)]
pub enum InputKind {
    // Keyboard
    KeyDown { scancode: u32, keycode: Key, modifiers: Modifiers },
    KeyUp { scancode: u32, keycode: Key, modifiers: Modifiers },
    TextInput { text: String },

    // Pointer (mouse/trackpad/touch unified)
    PointerMove { x: f32, y: f32, pressure: f32 },
    PointerDown { x: f32, y: f32, button: PointerButton },
    PointerUp { x: f32, y: f32, button: PointerButton },
    Scroll { dx: f32, dy: f32, natural: bool },

    // Touch gestures
    Pinch { scale: f32, center_x: f32, center_y: f32 },
    Rotate { angle_rad: f32, center_x: f32, center_y: f32 },
    Swipe { direction: SwipeDirection, fingers: u8, velocity: f32 },

    // Voice
    VoiceCommand { transcript: String, confidence: f32 },
    WakeWordDetected,

    // Gaze
    GazeFocus { x: f32, y: f32, dwell_ms: u32 },
    GazeSelect { x: f32, y: f32 },

    // System
    FocusGained,
    FocusLost,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Key {
    A, B, C, D, E, F, G, H, I, J, K, L, M,
    N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
    Num0, Num1, Num2, Num3, Num4, Num5, Num6, Num7, Num8, Num9,
    F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12,
    Escape, Tab, CapsLock, Shift, Control, Alt, Super, Space,
    Enter, Backspace, Delete, Insert, Home, End, PageUp, PageDown,
    ArrowUp, ArrowDown, ArrowLeft, ArrowRight,
    Grave, Minus, Equals, LeftBracket, RightBracket, Backslash,
    Semicolon, Apostrophe, Comma, Period, Slash,
    PrintScreen, ScrollLock, Pause,
    Unknown(u32),
}

#[derive(Debug, Clone, Copy, Default)]
pub struct Modifiers {
    pub shift: bool,
    pub control: bool,
    pub alt: bool,
    pub super_key: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PointerButton {
    Left,
    Right,
    Middle,
    Back,
    Forward,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SwipeDirection {
    Up, Down, Left, Right,
}
