//! Intel E1000 Ethernet Driver (basic)
//! Generated by Ollama qwen2.5-coder:32b, fixed by Taylor
//! Detects E1000 on PCI bus, reads MAC address.
//! Full packet TX/RX requires DMA ring buffers (later).

extern crate alloc;
use core::ptr::{read_volatile, write_volatile};

const VENDOR_INTEL: u16 = 0x8086;
const DEVICE_E1000: u16 = 0x100E;

// E1000 register offsets (in bytes)
const REG_CTRL: usize = 0x0000;
const REG_STATUS: usize = 0x0008;
const REG_EERD: usize = 0x0014;
const REG_RCTL: usize = 0x0100;
const REG_TCTL: usize = 0x0400;
const REG_RAL: usize = 0x5400;
const REG_RAH: usize = 0x5404;

pub struct E1000 {
    mmio_base: usize,
    pub mac: [u8; 6],
    pub link_up: bool,
}

impl E1000 {
    /// Read a register via MMIO
    fn read_reg(&self, offset: usize) -> u32 {
        unsafe { read_volatile((self.mmio_base + offset) as *const u32) }
    }

    /// Write a register via MMIO
    fn write_reg(&self, offset: usize, value: u32) {
        unsafe { write_volatile((self.mmio_base + offset) as *mut u32, value) }
    }

    /// Read MAC address from RAL/RAH registers
    fn read_mac(&mut self) {
        let ral = self.read_reg(REG_RAL);
        let rah = self.read_reg(REG_RAH);
        self.mac[0] = (ral & 0xFF) as u8;
        self.mac[1] = ((ral >> 8) & 0xFF) as u8;
        self.mac[2] = ((ral >> 16) & 0xFF) as u8;
        self.mac[3] = ((ral >> 24) & 0xFF) as u8;
        self.mac[4] = (rah & 0xFF) as u8;
        self.mac[5] = ((rah >> 8) & 0xFF) as u8;
    }

    /// Check link status
    fn check_link(&mut self) {
        let status = self.read_reg(REG_STATUS);
        self.link_up = status & 0x02 != 0; // Bit 1 = Link Up
    }

    /// Initialize the E1000
    pub fn init(mmio_base: usize) -> Self {
        let mut dev = E1000 {
            mmio_base,
            mac: [0; 6],
            link_up: false,
        };

        // Reset the device
        let ctrl = dev.read_reg(REG_CTRL);
        dev.write_reg(REG_CTRL, ctrl | (1 << 26)); // RST bit
        
        // Wait for reset
        for _ in 0..1000 {
            core::hint::spin_loop();
        }

        // Read MAC address
        dev.read_mac();
        
        // Check link
        dev.check_link();

        dev
    }

    /// Find E1000 on PCI bus
    pub fn detect(pci_devices: &[crate::pci::PciDevice]) -> Option<usize> {
        for dev in pci_devices {
            if dev.vendor_id == VENDOR_INTEL && dev.device_id == DEVICE_E1000 {
                // Read BAR0 for MMIO base address
                let bar0 = crate::pci::read_bar0(dev.bus, dev.device, dev.function);
                let mmio_base = (bar0 & 0xFFFFFFF0) as usize;
                return Some(mmio_base);
            }
        }
        None
    }

    pub fn mac_string(&self) -> alloc::string::String {
        alloc::String::from("info")
    }
}
