//! Aura Mesh — Multi-computer resource sharing
//! Generated by Ollama qwen2.5-coder:32b, cleaned by Taylor

extern crate alloc;
use alloc::string::String;
use alloc::vec::Vec;

pub const MESH_MAGIC: u32 = 0x41555241; // "AURA"

#[derive(Debug, Clone)]
pub struct MeshNode {
    pub id: u64,
    pub name: String,
    pub ip_addr: [u8; 4],
    pub capabilities: NodeCapabilities,
    pub state: NodeState,
    pub resources: ResourceUsage,
    pub last_seen: u64,
}

#[derive(Debug, Clone, Copy)]
pub struct NodeCapabilities {
    pub cpu_cores: u8,
    pub ram_mb: u32,
    pub gpu: bool,
    pub gpu_vram_mb: u32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NodeState {
    Online,
    Offline,
    Busy,
    Sleeping,
}

#[derive(Debug, Clone, Copy)]
pub struct ResourceUsage {
    pub cpu_percent: u8,
    pub ram_used_mb: u32,
    pub gpu_percent: u8,
}

/// Discovery packet for finding other AuraOS machines
#[derive(Debug, Clone)]
pub struct DiscoveryPacket {
    pub magic: u32,
    pub sender_id: u64,
    pub sender_name: [u8; 32],
    pub capabilities: NodeCapabilities,
    pub resources: ResourceUsage,
}

impl DiscoveryPacket {
    pub fn serialize(&self) -> Vec<u8> {
        let mut buf = Vec::with_capacity(64);
        buf.extend_from_slice(&self.magic.to_le_bytes());
        buf.extend_from_slice(&self.sender_id.to_le_bytes());
        buf.extend_from_slice(&self.sender_name);
        buf.push(self.capabilities.cpu_cores);
        buf.extend_from_slice(&self.capabilities.ram_mb.to_le_bytes());
        buf.push(if self.capabilities.gpu { 1 } else { 0 });
        buf.push(self.resources.cpu_percent);
        buf.extend_from_slice(&self.resources.ram_used_mb.to_le_bytes());
        buf
    }
}

pub struct MeshNetwork {
    pub nodes: Vec<MeshNode>,
    pub local_id: u64,
}

impl MeshNetwork {
    pub fn new(local_id: u64) -> Self {
        MeshNetwork {
            nodes: Vec::new(),
            local_id,
        }
    }

    pub fn add_node(&mut self, node: MeshNode) {
        if let Some(existing) = self.nodes.iter_mut().find(|n| n.id == node.id) {
            *existing = node;
        } else {
            self.nodes.push(node);
        }
    }

    pub fn remove_node(&mut self, id: u64) {
        self.nodes.retain(|n| n.id != id);
    }

    pub fn online_nodes(&self) -> Vec<&MeshNode> {
        self.nodes.iter().filter(|n| n.state == NodeState::Online).collect()
    }

    /// Find the best node for offloading compute
    pub fn best_compute_node(&self) -> Option<&MeshNode> {
        self.nodes.iter()
            .filter(|n| n.state == NodeState::Online && n.id != self.local_id)
            .filter(|n| n.resources.cpu_percent < 50)
            .max_by_key(|n| {
                let free_ram = n.capabilities.ram_mb.saturating_sub(n.resources.ram_used_mb);
                let free_cpu = 100u32.saturating_sub(n.resources.cpu_percent as u32);
                free_ram * free_cpu
            })
    }

    /// Total mesh resources
    pub fn total_resources(&self) -> (u32, u32, u8) {
        let total_ram: u32 = self.nodes.iter()
            .filter(|n| n.state == NodeState::Online)
            .map(|n| n.capabilities.ram_mb)
            .sum();
        let total_cores: u32 = self.nodes.iter()
            .filter(|n| n.state == NodeState::Online)
            .map(|n| n.capabilities.cpu_cores as u32)
            .sum();
        let gpu_count = self.nodes.iter()
            .filter(|n| n.state == NodeState::Online && n.capabilities.gpu)
            .count() as u8;
        (total_ram, total_cores, gpu_count)
    }
}
