//! PS/2 Mouse Driver
//! Generated by Ollama qwen2.5-coder:32b, fixed by Taylor
//! Polling-mode mouse driver (no interrupts needed)

use core::sync::atomic::{AtomicI32, AtomicU8, Ordering};

static MOUSE_X: AtomicI32 = AtomicI32::new(640);
static MOUSE_Y: AtomicI32 = AtomicI32::new(360);
static MOUSE_BUTTONS: AtomicU8 = AtomicU8::new(0);
static MOUSE_INITIALIZED: AtomicU8 = AtomicU8::new(0);

pub struct MouseState {
    pub x: i32,
    pub y: i32,
    pub left: bool,
    pub right: bool,
    pub middle: bool,
}

/// Get current mouse state
pub fn state() -> MouseState {
    MouseState {
        x: MOUSE_X.load(Ordering::Relaxed),
        y: MOUSE_Y.load(Ordering::Relaxed),
        left: MOUSE_BUTTONS.load(Ordering::Relaxed) & 1 != 0,
        right: MOUSE_BUTTONS.load(Ordering::Relaxed) & 2 != 0,
        middle: MOUSE_BUTTONS.load(Ordering::Relaxed) & 4 != 0,
    }
}

/// Wait for the PS/2 controller to be ready to receive
fn wait_write() {
    for _ in 0..100_000 {
        let status: u8 = unsafe {
            let mut port = x86_64::instructions::port::Port::<u8>::new(0x64);
            port.read()
        };
        if status & 2 == 0 { return; }
        core::hint::spin_loop();
    }
}

/// Wait for data to be available from PS/2 controller
fn wait_read() -> bool {
    for _ in 0..100_000 {
        let status: u8 = unsafe {
            let mut port = x86_64::instructions::port::Port::<u8>::new(0x64);
            port.read()
        };
        if status & 1 != 0 { return true; }
        core::hint::spin_loop();
    }
    false
}

/// Send a command to the PS/2 controller
fn controller_cmd(cmd: u8) {
    wait_write();
    unsafe {
        let mut port = x86_64::instructions::port::Port::<u8>::new(0x64);
        port.write(cmd);
    }
}

/// Send a byte to the PS/2 data port
fn data_write(data: u8) {
    wait_write();
    unsafe {
        let mut port = x86_64::instructions::port::Port::<u8>::new(0x60);
        port.write(data);
    }
}

/// Read a byte from the PS/2 data port
fn data_read() -> Option<u8> {
    if wait_read() {
        Some(unsafe {
            let mut port = x86_64::instructions::port::Port::<u8>::new(0x60);
            port.read()
        }
    } else {
        None
    }
}

/// Send a command to the mouse (via PS/2 controller wrapper)
fn mouse_cmd(cmd: u8) -> Option<u8> {
    controller_cmd(0xD4); // Write to auxiliary device
    data_write(cmd);
    data_read() // Should return 0xFA (ACK)
}

/// Initialize the PS/2 mouse
pub fn init(screen_width: i32, screen_height: i32) {
    // Center the mouse
    MOUSE_X.store(screen_width / 2, Ordering::Relaxed);
    MOUSE_Y.store(screen_height / 2, Ordering::Relaxed);
    
    // Enable auxiliary device (mouse)
    controller_cmd(0xA8);
    
    // Get compaq status byte
    controller_cmd(0x20);
    if let Some(status) = data_read() {
        let new_status = (status | 0x02) & !0x20; // Enable IRQ12, enable mouse clock
        controller_cmd(0x60); // Write command byte
        data_write(new_status);
    }
    
    // Set mouse defaults
    let _ = mouse_cmd(0xF6);
    
    // Enable data reporting
    let _ = mouse_cmd(0xF4);
    
    MOUSE_INITIALIZED.store(1, Ordering::Relaxed);
}

/// Poll for mouse data — call this from the main loop
/// Returns true if a mouse event was processed
pub fn poll(screen_width: i32, screen_height: i32) -> bool {
    if MOUSE_INITIALIZED.load(Ordering::Relaxed) == 0 {
        return false;
    }
    
    // Check if data is available AND it's from the mouse (bit 5 of status = aux data)
    let status: u8 = unsafe {
        let mut port = x86_64::instructions::port::Port::<u8>::new(0x64);
        port.read()
    };
    
    if status & 0x21 != 0x21 {
        // No mouse data available (need both data-ready AND aux-data flags)
        return false;
    }
    
    // Read 3-byte mouse packet
    let byte0 = unsafe {
        let mut port = x86_64::instructions::port::Port::<u8>::new(0x60);
        port.read()
    };
    
    // Validate: byte0 bit 3 should always be set in standard PS/2 mouse
    if byte0 & 0x08 == 0 {
        return false; // Not a valid first byte — resync
    }
    
    // Wait for bytes 2 and 3
    if !wait_read() { return false; }
    let byte1 = unsafe {
        let mut port = x86_64::instructions::port::Port::<u8>::new(0x60);
        port.read()
    };
    if !wait_read() { return false; }
    let byte2 = unsafe {
        let mut port = x86_64::instructions::port::Port::<u8>::new(0x60);
        port.read()
    };
    
    // Parse packet
    let buttons = byte0 & 0x07;
    
    // X movement (signed, with overflow check)
    let dx = if byte0 & 0x10 != 0 {
        // X sign bit set — negative
        byte1 as i32 - 256
    } else {
        byte1 as i32
    };
    
    // Y movement (signed, inverted — PS/2 Y is inverted from screen coords)
    let dy = if byte0 & 0x20 != 0 {
        // Y sign bit set — negative (but we invert)
        -(byte2 as i32 - 256)
    } else {
        -(byte2 as i32)
    };
    
    // Update position with bounds clamping
    let new_x = (MOUSE_X.load(Ordering::Relaxed) + dx).max(0).min(screen_width - 1);
    let new_y = (MOUSE_Y.load(Ordering::Relaxed) + dy).max(0).min(screen_height - 1);
    
    MOUSE_X.store(new_x, Ordering::Relaxed);
    MOUSE_Y.store(new_y, Ordering::Relaxed);
    MOUSE_BUTTONS.store(buttons, Ordering::Relaxed);
    
    true
)}
