//! PCI Bus Scanner
//! Generated by Ollama qwen2.5-coder:32b, fixed by Taylor
//! Scans PCI configuration space to detect hardware devices.

extern crate alloc;
use alloc::vec::Vec;

#[derive(Debug, Clone)]
pub struct PciDevice {
    pub bus: u8,
    pub device: u8,
    pub function: u8,
    pub vendor_id: u16,
    pub device_id: u16,
    pub class_code: u8,
    pub subclass: u8,
    pub prog_if: u8,
    pub header_type: u8,
    pub class_name: &'static str,
}

impl PciDevice {
    fn classify(class: u8, subclass: u8) -> &'static str {
        match (class, subclass) {
            (0x00, _) => "Unclassified",
            (0x01, 0x00) => "SCSI controller",
            (0x01, 0x01) => "IDE controller",
            (0x01, 0x05) => "ATA controller",
            (0x01, 0x06) => "SATA controller",
            (0x01, 0x08) => "NVMe controller",
            (0x01, _) => "Storage controller",
            (0x02, 0x00) => "Ethernet controller",
            (0x02, 0x80) => "Network controller",
            (0x02, _) => "Network controller",
            (0x03, 0x00) => "VGA controller",
            (0x03, 0x01) => "XGA controller",
            (0x03, 0x02) => "3D controller",
            (0x03, _) => "Display controller",
            (0x04, 0x00) => "Video device",
            (0x04, 0x01) => "Audio device",
            (0x04, 0x03) => "HD Audio",
            (0x04, _) => "Multimedia device",
            (0x05, _) => "Memory controller",
            (0x06, 0x00) => "Host bridge",
            (0x06, 0x01) => "ISA bridge",
            (0x06, 0x04) => "PCI-PCI bridge",
            (0x06, _) => "Bridge device",
            (0x07, _) => "Communication controller",
            (0x08, _) => "System peripheral",
            (0x09, _) => "Input device",
            (0x0C, 0x00) => "FireWire controller",
            (0x0C, 0x03) => "USB controller",
            (0x0C, 0x05) => "SMBus controller",
            (0x0C, _) => "Serial bus controller",
            (0x0D, _) => "Wireless controller",
            _ => "Unknown device",
        }
    }
}

/// Read a 32-bit value from PCI configuration space
fn pci_read(bus: u8, device: u8, function: u8, offset: u8) -> u32 {
    let address: u32 = (1u32 << 31)
        | ((bus as u32) << 16)
        | ((device as u32) << 11)
        | ((function as u32) << 8)
        | ((offset as u32) & 0xFC);
    
    unsafe {
        let mut addr_port = x86_64::instructions::port::Port::<u32>::new(0xCF8);
        let mut data_port = x86_64::instructions::port::Port::<u32>::new(0xCFC);
        addr_port.write(address);
        data_port.read()
    }
}

/// Scan all PCI buses and return found devices
pub fn scan() -> Vec<PciDevice> {
    let mut devices = Vec::new();

    for bus in 0u16..256 {
        for device in 0u8..32 {
            let id = pci_read(bus as u8, device, 0, 0);
            if id == 0xFFFFFFFF || id == 0 {
                continue;
            }

            let vendor_id = (id & 0xFFFF) as u16;
            let device_id = ((id >> 16) & 0xFFFF) as u16;
            
            // Check header type for multi-function
            let header = pci_read(bus as u8, device, 0, 0x0C);
            let header_type = ((header >> 16) & 0xFF) as u8;
            let multi_function = header_type & 0x80 != 0;
            
            let max_func = if multi_function { 8 } else { 1 };
            
            for function in 0..max_func {
                let id = if function == 0 {
                    id // Already read
                } else {
                    let fid = pci_read(bus as u8, device, function, 0);
                    if fid == 0xFFFFFFFF { continue; }
                    fid
                };

                let vendor_id = (id & 0xFFFF) as u16;
                let device_id = ((id >> 16) & 0xFFFF) as u16;
                
                let class_reg = pci_read(bus as u8, device, function, 0x08);
                let class_code = ((class_reg >> 24) & 0xFF) as u8;
                let subclass = ((class_reg >> 16) & 0xFF) as u8;
                let prog_if = ((class_reg >> 8) & 0xFF) as u8;

                devices.push(PciDevice {
                    bus: bus as u8,
                    device,
                    function,
                    vendor_id,
                    device_id,
                    class_code,
                    subclass,
                    prog_if,
                    header_type: header_type & 0x7F,
                    class_name: PciDevice::classify(class_code, subclass),
                });
            }
        }
    }

    devices
}

/// Format PCI device list for display
pub fn list_devices(devices: &[PciDevice]) {
    use crate::framebuffer;
    
    framebuffer::with_writer(|w| w.set_fg(0, 255, 180));
    
    for dev in devices {
        framebuffer::with_writer(|w| w.set_fg(200, 200, 200));
            dev.bus, dev.device, dev.function,
            dev.vendor_id, dev.device_id,
            dev.class_name);
    }
}

/// Read BAR0 from PCI config space
pub fn read_bar0(bus: u8, device: u8, function: u8) -> u32 {
    pci_read(bus, device, function, 0x10)
}
