//! USB Controller Detection via PCI
//! Generated by Ollama qwen2.5-coder:32b, cleaned by Taylor

extern crate alloc;
use alloc::vec::Vec;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UsbControllerType {
    UHCI,   // Universal Host Controller (USB 1.x)
    OHCI,   // Open Host Controller (USB 1.x)
    EHCI,   // Enhanced Host Controller (USB 2.0)
    XHCI,   // Extensible Host Controller (USB 3.x)
    Unknown(u8),
}

#[derive(Debug, Clone)]
pub struct UsbController {
    pub bus: u8,
    pub device: u8,
    pub function: u8,
    pub controller_type: UsbControllerType,
    pub base_address: u32,
}

impl UsbControllerType {
    pub fn from_prog_if(prog_if: u8) -> Self {
        match prog_if {
            0x00 => Self::UHCI,
            0x10 => Self::OHCI,
            0x20 => Self::EHCI,
            0x30 => Self::XHCI,
            other => Self::Unknown(other),
        }
    }

    pub fn name(&self) -> &'static str {
        match self {
            Self::UHCI => "UHCI (USB 1.x)",
            Self::OHCI => "OHCI (USB 1.x)",
            Self::EHCI => "EHCI (USB 2.0)",
            Self::XHCI => "XHCI (USB 3.x)",
            Self::Unknown(_) => "Unknown USB",
        }
    }
}

/// Detect USB controllers from PCI device list
pub fn detect(pci_devices: &[crate::pci::PciDevice]) -> Vec<UsbController> {
    let mut controllers = Vec::new();

    for dev in pci_devices {
        if dev.class_code == 0x0C && dev.subclass == 0x03 {
            let bar0 = crate::pci::read_bar0(dev.bus, dev.device, dev.function);
            controllers.push(UsbController {
                bus: dev.bus,
                device: dev.device,
                function: dev.function,
                controller_type: UsbControllerType::from_prog_if(dev.prog_if),
                base_address: bar0 & 0xFFFFFFF0,
            };
        }
    }

    controllers
)}
